name: PythonCalculator-CI
on:
  push:
    branches: ["main"]  # הענפים שיטריגו את התהליך
  pull_request:
    branches: ["main"]
env:
  IMAGE_NAME: python-calculator
  IMAGE_TAG: v${{ github.run_number }}.0
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Set Up Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'  # התאמה לגרסת Python ב-Dockerfile

      - name: Install application Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests
        run: |
          pytest addition-service/app/tests/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GHCR }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Changes in this Release:
            - Docker image built and pushed to GHCR
            - Image tag: ${{ env.IMAGE_TAG }}
            - Service: Python Calculator
          draft: false
          prerelease: false

      - name: Release Result
        if: success()
        run: |
          echo "Release created successfully!"
          echo "Release URL: ${{ steps.create_release.outputs.html_url }}"

      - name: Release Error
        if: failure()
        run: |
          echo "Failed to create release"